nextcloud/backup

lib/Command/PointList.php
lib/Command/PointRestore.php
lib/Exceptions/SqlParamsException.php
lib/Service/PointService.php
lib/SqlDump/SqlDumpMySQL.php
lib/SqlDump/SqlDumpPgSQL.php

- need to implemente pgsql connection test

improve restoring process with test & better confirmation step

---

lib/Command/ExternalAppData.php
lib/Controller/LocalController.php
lib/Db/PointRequest.php
lib/Model/RestoringChunk.php
lib/Service/ConfigService.php
lib/Service/PointService.php
lib/Service/RestoreService.php

also, fix a bug when unsetting external appdata that disable the app

backup:external:appdata --unset

---

lib/Service/ChunkService.php
lib/Service/PointService.php

store db_type in chunk

---

lib/Model/RestoringData.php
lib/Service/ChunkService.php
lib/Service/ConfigService.php
lib/Service/FilesService.php
lib/Service/PointService.php

add custom apps to backup

---

lib/Service/PackService.php
lib/Service/PointService.php

Signed-off-by: John Molakvoæ <skjnldsv@protonmail.com>

Fix php CS

---

lib/Command/PointList.php

~~also display comment even if signature cannot be confirmed.~~

display database type

---

lib/Command/PointRestore.php

display resume

---

package-lock.json
package.json

Reverts nextcloud/backup#64 as Node build fails for now

Revert "Bump @nextcloud/stylelint-config from 1.0.0-beta.0 to 2.0.1"

---

lib/Command/PointPurge.php
lib/Cron/Manage.php
lib/Service/ConfigService.php
lib/Service/CronService.php

store_items_external

---

src/components/GeneralSettingsSection.vue
src/models/SettingsModel.js

Signed-off-by: Louis Chemineau <louis@chmn.me>

Add inputs for store items

---

src/components/RestoringPointsListSection.vue

Signed-off-by: rakekniven <2069590+rakekniven@users.noreply.github.com>

Fixed typo

---

appinfo/info.xml
src/components/AppDataSection.vue
src/components/ExternalLocationsSection.vue

Reported at Transifex.
Signed-off-by: rakekniven <2069590+rakekniven@users.noreply.github.com>

Changed case of spelling

---

lib/Command/PointList.php
lib/Cron/Backup.php
lib/Cron/Manage.php
lib/Service/ConfigService.php
lib/Service/FilesService.php

- display colored text for Local instance in point:list,
- log some error in case of exception during cron,
- delay between health status check changed to 7d (from 12h)
- filters all logs from nextcloud, included incremented numbers,

List of small fixes/improvement

---

README.md

Signed-off-by: Valdnet <47037905+Valdnet@users.noreply.github.com>

Correct punctuation

---

src/components/GeneralSettingsSection.vue

Reported at Transifex.
Signed-off-by: rakekniven <2069590+rakekniven@users.noreply.github.com>

l10n: Fixed grammar

---

lib/Command/PointDownload.php
lib/Command/PointUpload.php
lib/Db/PointRequest.php
lib/Service/UploadService.php

- Locking restoring point during `upload` and `download`
- Fix also an issue with the lock/unlock sql request

lock during download/upload

---

src/components/GeneralSettingsSection.vue

Signed-off-by: Valdnet <47037905+Valdnet@users.noreply.github.com>

l10n: Change to a capital letter

---

lib/Cron/Backup.php
lib/Cron/Event.php
lib/Cron/Manage.php
lib/Exceptions/JobsTimeSlotException.php
lib/Service/ChunkService.php
lib/Service/ConfigService.php
lib/Service/CronService.php
lib/Service/ExternalFolderService.php
lib/Service/PackService.php
lib/Service/UploadService.php

this would avoid parallels runs on huge instance

lock during cron jobs

---

appinfo/info.xml

Currently this renders as a grey box in appstore and rss readers like nc news.
This change should remove the box.
Signed-off-by: rakekniven <2069590+rakekniven@users.noreply.github.com>

Changed indentation of feature listing

---

lib/Command/PointPurge.php
lib/Cron/Manage.php
lib/Service/CronService.php
lib/Service/PointService.php

there is a loop/inter-call when injecting some services. The fastest way to fix this was to move 2 methods from CronService into PointService.
- added a comment to improve the method itself.
@artonge

moving few method from cronService->pointService

---

lib/Service/ChunkService.php

cast int on $zipSize (float)

---

lib/Service/PointService.php

ignoring default apps folder when working on custom_apps

---

lib/Command/PointDownload.php

Provide missing metadataService for point download

---

lib/Service/ExternalFolderService.php

Patch to fix uninitialized parameter in ExternalFolderService

---

lib/SqlDump/SqlDumpMySQL.php
lib/SqlDump/SqlDumpPgSQL.php

Prevent unhandled exception when restoring sqldump

---

README.md

Updated Readme.md - fixed link to anchor

---

lib/Service/EncryptService.php

-sodium_memzero during cbc

---

lib/Service/UploadService.php

removing unused const

---

lib/Service/ConfigService.php

save setting STORE_ITEMS_EXTERNAL

---

Makefile
appinfo/info.xml

limit version to 24

---

src/components/GeneralSettingsSection.vue

Signed-off-by: Joas Schilling <coding@schilljs.com>

Fix plural handling

---

src/components/AppDataSection.vue
src/components/ExternalLocationsSection.vue
src/components/GeneralSettingsSection.vue

Signed-off-by: Louis Chemineau <louis@chmn.me>

Use the Button component from @nextcloud/vue

---

package-lock.json
package.json

Signed-off-by: Louis Chemineau <louis@chmn.me>

Clean package.json

---

lib/Tools/Traits/TDeserialize.php

confirm data is array

---

lib/Service/ExternalFolderService.php

Put restore point content upon new file creation

---

lib/Service/ExternalFolderService.php
lib/Service/PackService.php
lib/Service/PointService.php
lib/Service/UploadService.php
lib/Tools/ActivityPub/NCSignature.php
lib/Tools/Traits/TNCSignatory.php

fix multiple small issues related to uploading packed backup:
- fix the path of chunks and parts,
- fix an issue with signature,
- fix small occ command displayed string

better upload

---

lib/Command/PointRestore.php
lib/Service/ChunkService.php

Seems that getting Stream from an external method is not ok anymore

fix stream from sqldump zip file

---

.github/workflows/dependabot-approve-merge.yml
package-lock.json
package.json
src/adminSettings.js
src/components/AppDataSection.vue
src/components/ExternalLocationsSection.vue
src/components/GeneralSettingsSection.vue
src/components/RestoringPointsListSection.vue
src/views/BackupAdminSettings.vue

Might also fix dependabot updates, not sure why it is not running on stable24
Fix https://github.com/nextcloud/backup/issues/412

Cleanup package.json

---

lib/SqlDump/SqlDumpMySQL.php

Added support for different mysql ports + using correct constants
